### ISSUE TITLE
Is is possible to get a config looks like this?

### ISSUE THREAD

**Issue by ntd1712** [m1/Vars#19]
For example, I have a config file named **db.yml** that contains:
```
db:
  default: mysql
  connections:
    mysql:
      driver: pdo_mysql
      host: localhost
      port: 3306
      dbname: forge
      user: forge
      password:
      unix_socket:
      charset: utf8
      prefix:
```

Then, I'll use it:
```
$vars = new Vars(__DIR__.'/config/db.yml');
$connection = $vars->get('db.connections[db.default]');
```

Is is possible to get a config looks like this?
**$vars->get('db.connections[db.default]');**

Instead of the normal way:
**$vars->get('db.connections')[$vars->get('db.default')];**
